# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 16:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='C\xe9dula')),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('anio_ingreso', models.IntegerField()),
                ('numero_celular', models.CharField(max_length=20)),
                ('tipo_celular', models.CharField(choices=[('Movistar', 'Movistar'), ('Claro', 'Claro')], max_length=20)),
                ('acceso_internet', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('estado_civil', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Acompa\xf1ado(a)', 'Acompa\xf1ado(a)'), ('Viudo(a)', 'Viudo(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=20)),
                ('comunidad', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipio', chained_model_field='municipio', on_delete=django.db.models.deletion.CASCADE, to='lugar.Comunidad')),
                ('lugar_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
            ],
            options={
                'verbose_name_plural': 'I. Datos generales del/la afiliado/a',
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '\xc1rea',
                'verbose_name_plural': '\xc1reas',
            },
        ),
        migrations.CreateModel(
            name='AreasFinca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mz', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Areas')),
            ],
            options={
                'verbose_name': '\xc1rea de la Finca (Mzs)',
            },
        ),
        migrations.CreateModel(
            name='DatosFamiliares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=300)),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=20)),
                ('edad', models.IntegerField()),
                ('escolaridad', models.CharField(max_length=300, verbose_name='Escolaridad (\xdaltimo a\xf1o de escolaridad)')),
                ('parentesco', models.CharField(max_length=200)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Afiliado')),
            ],
            options={
                'verbose_name_plural': 'Datos Familiares',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Documento de propiedad',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_encuesta', models.DateField()),
                ('anio', models.IntegerField(editable=False)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Afiliado')),
            ],
            options={
                'verbose_name_plural': 'II. Encuestas',
            },
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolaridad', models.CharField(choices=[('Alfabetizado', 'Alfabetizado'), ('Lee y Escribe', 'Lee y Escribe'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universitario', 'Universitario')], max_length=20)),
                ('respuesta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Afiliado')),
            ],
            options={
                'verbose_name': 'Escolaridad',
            },
        ),
        migrations.CreateModel(
            name='FamiliaEmigra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hombres', models.IntegerField()),
                ('mujeres', models.IntegerField()),
                ('donde_emigran', models.CharField(choices=[('Local', 'Local'), ('Nacional', 'Nacional'), ('Centroam\xe9rica', 'Centroam\xe9rica'), ('Internacional', 'Internacional')], max_length=25)),
                ('tiempo', models.CharField(choices=[('', ''), ('', '')], max_length=25)),
                ('meses', multiselectfield.db.fields.MultiSelectField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=88)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Afiliado')),
            ],
            options={
                'verbose_name_plural': 'Cu\xe1ntos miembros de la familia emigran',
            },
        ),
        migrations.CreateModel(
            name='FormaTenencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalizada', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Origen de la Propiedad',
            },
        ),
        migrations.CreateModel(
            name='OrigenPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Origen')),
            ],
        ),
        migrations.CreateModel(
            name='OtrasTierras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mz', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Areas')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name': 'Otras tierras que trabaja (Mzs)',
            },
        ),
        migrations.CreateModel(
            name='PersonasDependen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('Adultos: Hombres', 'Adultos: Hombres'), ('Adultos: Mujeres', 'Adultos: Mujeres'), ('Ni\xf1as menores de 12 a\xf1os', 'Ni\xf1as menores de 12 a\xf1os'), ('Ni\xf1os menores de 12 a\xf1os', 'Ni\xf1os menores de 12 a\xf1os')], max_length=25)),
                ('cantidad', models.IntegerField()),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Afiliado')),
            ],
            options={
                'verbose_name': 'Personas que dependen del afiliado',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profecion', models.CharField(max_length=200)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Afiliado')),
            ],
            options={
                'verbose_name': 'Profesi\xf3n',
            },
        ),
        migrations.AddField(
            model_name='documentopropiedad',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='areasfinca',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
    ]
