# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:58
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import smart_selects.db_fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lugar', '0002_auto_20170712_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='C\xe9dula')),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=250)),
                ('foto', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='productores/')),
                ('anio_ingreso', models.IntegerField(verbose_name='A\xf1o ingreso')),
                ('numero_celular', models.CharField(max_length=20)),
                ('tipo_celular', models.CharField(choices=[('Movistar', 'Movistar'), ('Claro', 'Claro')], max_length=20)),
                ('edad', models.IntegerField(editable=False)),
                ('comunidad', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipio', chained_model_field='municipio', on_delete=django.db.models.deletion.CASCADE, to='lugar.Comunidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Municipio')),
            ],
            options={
                'verbose_name_plural': 'I. Datos generales del/la afiliado/a',
            },
        ),
        migrations.CreateModel(
            name='Agricultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_sembrada', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='\xc1rea sembrada(Mz)')),
                ('produccion_total', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Producci\xf3n Total qq')),
                ('semillas', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Semilla qq')),
                ('consumo_humano', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumo humano qq')),
                ('consumo_animal', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumo animal qq')),
                ('venta', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Venta qq')),
                ('costo_produccion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Costo de producci\xf3n (Inversi\xf3n) C$/Mz')),
                ('ingresos_produccion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ingresos de la producci\xf3n C$/Mz')),
                ('ganancia_perdida', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ganancia o Perdida C$/Mz')),
                ('tipo', models.CharField(choices=[('Cultivo de primera', 'Cultivo de primera'), ('Cultivo de postrera', 'Cultivo de postrera'), ('Cultivo de apante', 'Cultivo de apante'), ('Cultivos permanentes (Frutales, C\xedtricos, \u2026)', 'Cultivos permanentes (Frutales, C\xedtricos, \u2026)'), ('Otros', 'Otros')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Agricultura',
            },
        ),
        migrations.CreateModel(
            name='AreasFinca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mz', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Areas')),
            ],
            options={
                'verbose_name_plural': '\xc1rea de la Finca (Mzs)',
            },
        ),
        migrations.CreateModel(
            name='BeneficiadoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
            ],
            options={
                'verbose_name_plural': '\xbfEs beneficiado por otros proyectos o programa del gobierno?',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
            ],
            options={
                'verbose_name_plural': '\xbfCotiza?',
            },
        ),
        migrations.CreateModel(
            name='CotizacionOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('acciones_cambio_climatico', models.ManyToManyField(blank=True, to='configuracion.CambioClimatico', verbose_name='Acciones que realiza para enfrentar el cambio clim\xe1tico')),
                ('afiliacion_unag', models.ManyToManyField(blank=True, to='configuracion.AfiliacionUnag', verbose_name='Motivos de Afiliaci\xf3n a la UNAG')),
            ],
            options={
                'verbose_name': 'Cotizaci\xf3n y Organizaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
            ],
            options={
                'verbose_name_plural': '\xbfRecibe cr\xe9dito?',
            },
        ),
        migrations.CreateModel(
            name='DatosFamiliares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=300)),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('escolaridad', models.CharField(max_length=300, verbose_name='Escolaridad (\xdaltimo a\xf1o de escolaridad)')),
                ('parentesco', models.CharField(max_length=200)),
                ('edad', models.IntegerField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Datos Familiares',
            },
        ),
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso_internet', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('estado_civil', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Acompa\xf1ado(a)', 'Acompa\xf1ado(a)'), ('Viudo(a)', 'Viudo(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Datos generales',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Documento')),
            ],
            options={
                'verbose_name_plural': 'Documento de propiedad que posee',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_encuesta', models.DateField()),
                ('anio', models.IntegerField(editable=False)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Afiliado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'II. Encuestas',
            },
        ),
        migrations.CreateModel(
            name='EnergiaElectrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': '\xbfTiene acceso a Energ\xeda El\xe9ctrica?',
            },
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolaridad', models.CharField(choices=[('Alfabetizado', 'Alfabetizado'), ('Lee y Escribe', 'Lee y Escribe'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universitario', 'Universitario')], max_length=20)),
                ('respuesta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Escolaridad afiliado',
            },
        ),
        migrations.CreateModel(
            name='FamiliaEmigra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hombres', models.IntegerField()),
                ('mujeres', models.IntegerField()),
                ('donde_emigran', models.CharField(choices=[('Local', 'Local'), ('Nacional', 'Nacional'), ('Centroam\xe9rica', 'Centroam\xe9rica'), ('Internacional', 'Internacional')], max_length=25)),
                ('tiempo', models.CharField(choices=[('< 1 mes', '< 1 mes'), ('1-3 meses', '1-3 meses'), ('4-6 meses', '4-6 meses'), ('7-12 meses', '7-12 meses'), ('> 12 meses', '> 12 meses')], max_length=25)),
                ('meses', multiselectfield.db.fields.MultiSelectField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=88)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Cu\xe1ntos miembros de la familia emigran',
            },
        ),
        migrations.CreateModel(
            name='FormaTenencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalizada', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Forma de Tenencia',
            },
        ),
        migrations.CreateModel(
            name='Infraestructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possee', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Infraestructuras')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioAnimales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cuanto_vende', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Animales')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Inventario de animales',
            },
        ),
        migrations.CreateModel(
            name='ManoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mano_obra', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': '\xbfContrata mano de obra?',
            },
        ),
        migrations.CreateModel(
            name='MiembroCooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('cooperativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Cooperativa')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': '\xbfEs miembro de Cooperativa?',
            },
        ),
        migrations.CreateModel(
            name='OrigenPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Origen')),
            ],
            options={
                'verbose_name_plural': 'Origen de la Propiedad',
            },
        ),
        migrations.CreateModel(
            name='OtrasTierras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mz', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Areas')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Otras tierras que trabaja (Mzs)',
            },
        ),
        migrations.CreateModel(
            name='PersonasDependen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(choices=[('Adultos: Hombres', 'Adultos: Hombres'), ('Adultos: Mujeres', 'Adultos: Mujeres'), ('Ni\xf1as menores de 12 a\xf1os', 'Ni\xf1as menores de 12 a\xf1os'), ('Ni\xf1os menores de 12 a\xf1os', 'Ni\xf1os menores de 12 a\xf1os')], max_length=25)),
                ('cantidad', models.IntegerField()),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Personas que dependen del afiliado',
            },
        ),
        migrations.CreateModel(
            name='ProduccionHuevosLeche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produccion', models.CharField(choices=[('Producci\xf3n de huevos por mes', 'Producci\xf3n de huevos por mes'), ('Producci\xf3n de leche (litros por d\xeda)', 'Producci\xf3n de leche (litros por d\xeda)')], max_length=40)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cuanto_vende', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quien_vende', models.CharField(choices=[('Intermediarios', 'Intermediarios'), ('Estado', 'Estado'), ('Mercado local', 'Mercado local'), ('Otros', 'Otros')], max_length=20)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Producci\xf3n de huevos y leche',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profecion', models.CharField(max_length=200)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Profesi\xf3n',
            },
        ),
        migrations.CreateModel(
            name='RespuestaSiCotiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_cuando', models.CharField(choices=[('Menor 1 a\xf1o', 'Menor 1 a\xf1o'), ('Mas de 1 a\xf1o', 'Mas de 1 a\xf1o')], max_length=25)),
                ('cuanto_cotiza', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('frecuencia', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=25)),
                ('donde_cotiza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.DondeCotiza')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Si la respuesta es SI',
            },
        ),
        migrations.CreateModel(
            name='SistemaAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
                ('sistema', models.ManyToManyField(to='configuracion.Sistema')),
            ],
            options={
                'verbose_name_plural': 'Sistema de Agua Utilizado para la finca y consumo',
            },
        ),
        migrations.CreateModel(
            name='TablaEmpleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporal_hombres', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('temporal_mujeres', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('permanente_hombres', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('permanente_mujeres', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('familiar_hombres', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('familiar_mujeres', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Cultivo')),
            ],
            options={
                'verbose_name_plural': 'Empleo',
            },
        ),
        migrations.CreateModel(
            name='VendeProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', multiselectfield.db.fields.MultiSelectField(choices=[('Intermediario', 'Intermediario'), ('Al estado', 'Al estado'), ('Consumidor/Mercado local', 'Consumidor/Mercado local')], max_length=48)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': '\xbfA qui\xe9n vende su producci\xf3n?',
            },
        ),
        migrations.AddField(
            model_name='documentopropiedad',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='datosfamiliares',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='credito',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='credito',
            name='formas_recibe_credito',
            field=models.ManyToManyField(blank=True, to='configuracion.FormasCredito'),
        ),
        migrations.AddField(
            model_name='credito',
            name='proyectos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.RecibeCredito', verbose_name='De quien recibe el credito'),
        ),
        migrations.AddField(
            model_name='cotizacionorganizacion',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='cotizacionorganizacion',
            name='problemas_productor',
            field=models.ManyToManyField(blank=True, to='configuracion.ProblemasProductor', verbose_name='Problemas m\xe1s sentidos como productor'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='beneficiadoproyecto',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='beneficiadoproyecto',
            name='proyectos',
            field=models.ManyToManyField(blank=True, to='configuracion.Proyecto'),
        ),
        migrations.AddField(
            model_name='areasfinca',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='agricultura',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta'),
        ),
        migrations.AddField(
            model_name='agricultura',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Cultivo'),
        ),
    ]
