# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 14:42
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infraestructura',
            name='possee',
        ),
        migrations.AlterField(
            model_name='vendeproduccion',
            name='respuesta',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Intermediario', 'Intermediario'), ('Al estado', 'Al estado'), ('Consumidor / Mercado local', 'Consumidor / Mercado local'), ('Mercado nacional', 'Mercado nacional'), ('Mercado internacional / Exportaci\xf3n', 'Mercado internacional / Exportaci\xf3n')], max_length=103),
        ),
    ]
