# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escolaridad',
            options={'verbose_name_plural': 'Escolaridad afiliado'},
        ),
        migrations.AlterModelOptions(
            name='personasdependen',
            options={'verbose_name_plural': 'Personas que dependen del afiliado'},
        ),
        migrations.AlterModelOptions(
            name='profesion',
            options={'verbose_name_plural': 'Profesi\xf3n'},
        ),
        migrations.RemoveField(
            model_name='datosgenerales',
            name='edad',
        ),
    ]
