# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 16:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_sembrada', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='\xc1rea sembrada(Mz)')),
                ('produccion_total', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Producci\xf3n Total qq')),
                ('semillas', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Semilla qq')),
                ('consumo_humano', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumo humano qq')),
                ('consumo_animal', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumo animal qq')),
                ('venta', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Venta qq')),
                ('costo_produccion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Costo de producci\xf3n (Inversi\xf3n) C$/Mz')),
                ('ingresos_produccion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ingresos de la producci\xf3n C$/Mz')),
                ('ganancia_perdida', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ganancia o Perdida C$/Mz')),
                ('tipo', models.CharField(choices=[('Cultivo de primera', 'Cultivo de primera'), ('Cultivo de postrera', 'Cultivo de postrera'), ('Cultivo de apante', 'Cultivo de apante'), ('Cultivos permanentes (Frutales, C\xedtricos, \u2026)', 'Cultivos permanentes (Frutales, C\xedtricos, \u2026)'), ('Otros', 'Otros')], max_length=30)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Agricultura',
            },
        ),
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Animales',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Cultivos',
            },
        ),
        migrations.CreateModel(
            name='EnergiaElectrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': '\xbfTiene acceso a Energ\xeda El\xe9ctrica?',
            },
        ),
        migrations.CreateModel(
            name='InventarioAnimales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cuanto_vende', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Animales')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Inventario de animales',
            },
        ),
        migrations.CreateModel(
            name='ProduccionHuevosLeche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produccion', models.CharField(choices=[('Producci\xf3n de huevos por mes', 'Producci\xf3n de huevos por mes'), ('Producci\xf3n de leche (litros por d\xeda)', 'Producci\xf3n de leche (litros por d\xeda)')], max_length=40)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cuanto_vende', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quien_vende', models.CharField(choices=[('Intermediarios', 'Intermediarios'), ('Estado', 'Estado'), ('Mercado local', 'Mercado local'), ('Otros', 'Otros')], max_length=20)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Producci\xf3n de huevos y leche',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Sistema de Agua',
            },
        ),
        migrations.CreateModel(
            name='SistemaAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
                ('sistema', models.ManyToManyField(to='productores.Sistema')),
            ],
            options={
                'verbose_name_plural': 'Sistema de Agua Utilizado para la finca y consumo',
            },
        ),
        migrations.AlterModelOptions(
            name='areasfinca',
            options={'verbose_name_plural': '\xc1rea de la Finca (Mzs)'},
        ),
        migrations.AlterModelOptions(
            name='documentopropiedad',
            options={'verbose_name_plural': 'Documento de propiedad que posee'},
        ),
        migrations.AlterModelOptions(
            name='formatenencia',
            options={'verbose_name_plural': 'Forma de Tenencia'},
        ),
        migrations.AlterModelOptions(
            name='origenpropiedad',
            options={'verbose_name_plural': 'Origen de la Propiedad'},
        ),
        migrations.AlterModelOptions(
            name='otrastierras',
            options={'verbose_name_plural': 'Otras tierras que trabaja (Mzs)'},
        ),
        migrations.AlterField(
            model_name='areasfinca',
            name='mz',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='otrastierras',
            name='mz',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='agricultura',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Cultivo'),
        ),
    ]
