# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='anio_ingreso',
            field=models.IntegerField(blank=True, null=True, verbose_name='A\xf1o ingreso'),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='tipo_celular',
            field=models.CharField(blank=True, choices=[('Movistar', 'Movistar'), ('Claro', 'Claro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='costo_produccion',
            field=models.FloatField(verbose_name='Costo de producci\xf3n (Inversi\xf3n) C$/Mz'),
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='ganancia_perdida',
            field=models.FloatField(verbose_name='Ganancia o Perdida C$/Mz'),
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='ingresos_produccion',
            field=models.FloatField(verbose_name='Ingresos de la producci\xf3n C$/Mz'),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='acceso_internet',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vendeproduccion',
            name='respuesta',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Intermediario', 'Intermediario'), ('Al estado', 'Al estado'), ('Consumidor / Mercado local', 'Consumidor / Mercado local'), ('Mercado nacional', 'Mercado nacional'), ('Exportaci\xf3n', 'Exportaci\xf3n')], max_length=79),
        ),
    ]
