# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-23 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionfinca2',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
