# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('productores', '0002_auto_20170825_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembrocooperativa',
            name='cooperativa',
        ),
        migrations.AddField(
            model_name='miembrocooperativa',
            name='cooperativa',
            field=models.ManyToManyField(blank=True, null=True, to='configuracion.Cooperativa'),
        ),
    ]
