# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20170908_0810'),
        ('productores', '0002_auto_20170905_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierrasAlquiladas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posse', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Posse tierras alquiladas',
            },
        ),
        migrations.RemoveField(
            model_name='escolaridad',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='agricultura',
            name='quien_vende',
            field=models.CharField(choices=[('Intermediario', 'Intermediario'), ('Al estado', 'Al estado'), ('Consumidor / Mercado local', 'Consumidor / Mercado local'), ('Mercado nacional', 'Mercado nacional'), ('Mercado internacional / Exportaci\xf3n', 'Mercado internacional / Exportaci\xf3n')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areasfinca',
            name='origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Origen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosfamiliares',
            name='donde_emigran',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Nacional', 'Nacional'), ('Centroam\xe9rica', 'Centroam\xe9rica'), ('Internacional', 'Internacional')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='datosfamiliares',
            name='meses',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=88),
        ),
        migrations.AddField(
            model_name='datosfamiliares',
            name='tiempo',
            field=models.CharField(blank=True, choices=[('< 1 mes', '< 1 mes'), ('1-3 meses', '1-3 meses'), ('4-6 meses', '4-6 meses'), ('7-12 meses', '7-12 meses'), ('> 12 meses', '> 12 meses')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='escolaridad',
            name='nivel_escolaridad',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universitario', 'Universitario')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='escolaridad',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universitario', 'Universitario')], max_length=300, verbose_name='Escolaridad (\xdaltimo a\xf1o de escolaridad)'),
        ),
        migrations.AlterField(
            model_name='escolaridad',
            name='escolaridad',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20, verbose_name='Lee y escribe'),
        ),
        migrations.AlterField(
            model_name='profesion',
            name='profecion',
            field=models.CharField(max_length=200, verbose_name='Profesi\xf3n'),
        ),
    ]
