# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0003_direccionfinca'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesamiento',
            name='cuanto_vende',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
