# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0003_auto_20170908_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosfamiliares',
            name='parentesco',
            field=models.CharField(choices=[('Abuela', 'Abuela'), ('Abuelo', 'Abuelo'), ('Bisabuela', 'Bisabuela'), ('Bisabuelo', 'Bisabuelo'), ('Cu\xf1ada', 'Cu\xf1ada'), ('Cu\xf1ado', 'Cu\xf1ado'), ('Esposa', 'Esposa'), ('Esposo', 'Esposo'), ('Hermana', 'Hermana'), ('Hermano', 'Hermano'), ('Hija', 'Hija'), ('Hijo', 'Hijo'), ('Madre', 'Madre'), ('Nuera', 'Nuera'), ('Padre', 'Padre'), ('Pareja', 'Pareja'), ('Prima', 'Prima'), ('Primo', 'Primo'), ('Sobrina', 'Sobrina'), ('Sobrino', 'Sobrino'), ('Suegra', 'Suegra'), ('Suegro', 'Suegro'), ('T\xeda', 'T\xeda'), ('T\xedo', 'T\xedo'), ('Yerno', 'Yerno'), ('Otro', 'Otro')], max_length=200),
        ),
        migrations.AlterField(
            model_name='escolaridad',
            name='nivel_escolaridad',
            field=models.CharField(blank=True, choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universitario', 'Universitario')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tierrasalquiladas',
            name='posse',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=20, verbose_name='Posee'),
        ),
    ]
