# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0005_auto_20170920_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiaemigra',
            name='donde_emigran',
        ),
        migrations.RemoveField(
            model_name='familiaemigra',
            name='meses',
        ),
        migrations.RemoveField(
            model_name='familiaemigra',
            name='tiempo',
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='anio_ingreso',
            field=models.IntegerField(blank=True, null=True, verbose_name='A\xf1o Ingreso UNAG'),
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='quien_vende',
            field=models.CharField(choices=[('Intermediario', 'Intermediario'), ('Al estado', 'Al estado'), ('Consumidor / Mercado local', 'Consumidor / Mercado local'), ('Mercado nacional', 'Mercado nacional'), ('Mercado internacional / Exportaci\xf3n', 'Mercado internacional / Exportaci\xf3n'), ('No vende', 'No vende')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='escolaridad',
            field=models.CharField(choices=[('No estudia', 'No estudia'), ('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universitario', 'Universitario')], max_length=300, verbose_name='Escolaridad (\xdaltimo a\xf1o de escolaridad)'),
        ),
        migrations.AlterField(
            model_name='escolaridad',
            name='nivel_escolaridad',
            field=models.CharField(blank=True, choices=[('No estudia', 'No estudia'), ('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universitario', 'Universitario')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produccionhuevosleche',
            name='quien_vende',
            field=models.CharField(choices=[('Intermediarios', 'Intermediarios'), ('Estado', 'Estado'), ('Mercado local', 'Mercado local'), ('Otros', 'Otros'), ('No vende', 'No vende')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vendeproduccion',
            name='respuesta',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Intermediario', 'Intermediario'), ('Al estado', 'Al estado'), ('Consumidor / Mercado local', 'Consumidor / Mercado local'), ('Mercado nacional', 'Mercado nacional'), ('Mercado internacional / Exportaci\xf3n', 'Mercado internacional / Exportaci\xf3n'), ('No vende', 'No vende')], max_length=112),
        ),
    ]
