# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0006_auto_20171006_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='ronda',
            field=models.IntegerField(choices=[(1, 'Ronda I'), (2, 'Ronda II'), (3, 'Ronda III'), (4, 'Ronda IV'), (5, 'Ronda V')], default=1),
            preserve_default=False,
        ),
    ]
