# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-06 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0008_auto_20180316_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acuicola',
            options={'verbose_name_plural': 'Piscicultura/Acu\xedcolas'},
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='costo_produccion',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo de producci\xf3n (Inversi\xf3n) C$/Mz'),
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='ganancia_perdida',
            field=models.FloatField(blank=True, null=True, verbose_name='Ganancia o Perdida C$/Mz'),
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='ingresos_produccion',
            field=models.FloatField(blank=True, null=True, verbose_name='Ingresos de la producci\xf3n C$/Mz'),
        ),
    ]
