# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-09 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0010_auto_20181109_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembrobancosemilla',
            old_name='cooperativa',
            new_name='banco_semillas',
        ),
    ]
