# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-13 16:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0011_auto_20181109_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembrobancosemilla',
            options={'verbose_name_plural': '\xbfEs miembro de Bancos de Semillas?'},
        ),
        migrations.RemoveField(
            model_name='agricultura',
            name='costo_produccion',
        ),
        migrations.RemoveField(
            model_name='agricultura',
            name='ganancia_perdida',
        ),
        migrations.RemoveField(
            model_name='agricultura',
            name='ingresos_produccion',
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='consumo_animal',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumo animal'),
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='consumo_humano',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumo humano'),
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='produccion_total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Producci\xf3n Total'),
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='semillas',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Semilla'),
        ),
        migrations.AlterField(
            model_name='agricultura',
            name='venta',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Venta'),
        ),
    ]
