# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_tipoenergia'),
        ('productores', '0013_auto_20181113_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionFinca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Direcci\xf3n de la finca',
            },
        ),
        migrations.CreateModel(
            name='OtrosTiposEnergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.TipoEnergia')),
            ],
            options={
                'verbose_name_plural': 'Otro Tipo de energ\xeda',
            },
        ),
        migrations.AddField(
            model_name='profesion',
            name='promotor',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=2, null=True, verbose_name='Promotor/a'),
        ),
        migrations.RemoveField(
            model_name='credito',
            name='proyectos',
        ),
        migrations.AddField(
            model_name='credito',
            name='proyectos',
            field=models.ManyToManyField(blank=True, to='configuracion.RecibeCredito', verbose_name='De quien recibe el credito'),
        ),
        migrations.AlterField(
            model_name='datosfamiliares',
            name='parentesco',
            field=models.CharField(choices=[('Abuela', 'Abuela'), ('Abuelo', 'Abuelo'), ('Bisabuela', 'Bisabuela'), ('Bisabuelo', 'Bisabuelo'), ('Cuniada', 'Cu\xf1ada'), ('Cuniado', 'Cu\xf1ado'), ('Esposa', 'Esposa'), ('Esposo', 'Esposo'), ('Hermana', 'Hermana'), ('Hermano', 'Hermano'), ('Hija', 'Hija'), ('Hijo', 'Hijo'), ('Madre', 'Madre'), ('Nuera', 'Nuera'), ('Padre', 'Padre'), ('Pareja', 'Pareja'), ('Prima', 'Prima'), ('Primo', 'Primo'), ('Sobrina', 'Sobrina'), ('Sobrino', 'Sobrino'), ('Suegra', 'Suegra'), ('Suegro', 'Suegro'), ('Tia', 'T\xeda'), ('Tio', 'T\xedo'), ('Yerno', 'Yerno'), ('Nieto', 'Nieto'), ('Nieta', 'Nieta'), ('Otro', 'Otro')], max_length=200),
        ),
        migrations.AlterField(
            model_name='produccionhuevosleche',
            name='tipo_produccion',
            field=models.CharField(choices=[('Producci\xf3n de leche (litros por d\xeda)', 'Leche (litros por d\xeda)'), ('Queso (qq/mes)', 'Queso (qq/mes)'), ('Producci\xf3n de carne (kg/a\xf1o)', 'Carne de res (kg, lbs/a\xf1o)'), ('Cuajada libras por d\xeda', 'Cuajada libras por d\xeda'), ('Leche agria (litros/d\xeda)', 'Leche agria (litros/d\xeda)'), ('Yogurt (litros/d\xeda)', 'Yogurt (litros/d\xeda)'), ('Quesillos libras/d\xeda', 'Quesillos libras/d\xeda'), ('Crema Libras por d\xeda', 'Crema Libras por d\xeda'), ('Producci\xf3n de huevos por mes', 'Huevos (und/mes)'), ('Carne Av\xedcola (lbs/mes)', 'Carne Av\xedcola (lbs/mes)'), ('Carne de cerdo (lbs/a\xf1o)', 'Carne de cerdo (lbs/a\xf1o)'), ('Carne de pelibuey lbs/a\xf1o', 'Carne de pelibuey lbs/a\xf1o'), ('Leche de cabra (litros/d\xeda)', 'Leche de cabra (litros/d\xeda)'), ('Queso Caprino (qq/mes)', 'Queso Caprino (qq/mes)'), ('Producci\xf3n de miel (lt/a\xf1o)', 'Miel (lt/a\xf1o)'), ('Producci\xf3n de pez (kg/a\xf1o)', 'Pez (kg/a\xf1o)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesion',
            name='profecion',
            field=models.CharField(max_length=200, verbose_name='Profesi\xf3n/Ocupaci\xf3n'),
        ),
    ]
