# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_productosprocesados'),
        ('productores', '0014_auto_20190508_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procesamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantiddad', models.FloatField(verbose_name='Cantidad al mes')),
                ('quien_vende', models.CharField(choices=[('Intermediario', 'Intermediario'), ('Al estado', 'Al estado'), ('Consumidor / Mercado local', 'Consumidor / Mercado local'), ('Mercado nacional', 'Mercado nacional'), ('Mercado internacional / Exportaci\xf3n', 'Mercado internacional / Exportaci\xf3n'), ('No vende', 'No vende')], max_length=50)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.ProductosProcesados')),
            ],
            options={
                'verbose_name_plural': 'Realiza procesamiento o agregaci\xf3n de valor a rubros agropecuarios en la finca',
            },
        ),
    ]
