# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0016_auto_20190521_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionFinca2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.Encuesta')),
            ],
            options={
                'verbose_name_plural': 'Direcci\xf3n de la finca',
            },
        ),
        migrations.RemoveField(
            model_name='direccionfinca',
            name='encuesta',
        ),
        migrations.DeleteModel(
            name='DireccionFinca',
        ),
    ]
