# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-23 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfiliacionUnag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Motivos de Afiliaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Animales',
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': '\xc1rea',
                'verbose_name_plural': '\xc1reas',
            },
        ),
        migrations.CreateModel(
            name='BancoSemilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Bancos de Semillas',
            },
        ),
        migrations.CreateModel(
            name='CambioClimatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Acciones cambio clim\xe1tico',
            },
        ),
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Cooperativas',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('unidad_medida', models.IntegerField(blank=True, choices=[(1, 'Quintal'), (2, 'Kilogramos'), (3, 'Libras'), (4, 'Docena'), (5, 'Unidad')], null=True)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Cultivos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Documento de propiedad',
            },
        ),
        migrations.CreateModel(
            name='DondeCotiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Donde cotiza',
            },
        ),
        migrations.CreateModel(
            name='FormasCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Formas en que recibe cr\xe9dito',
            },
        ),
        migrations.CreateModel(
            name='Infraestructuras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Infraestructuras',
            },
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Origen de la Propiedad',
            },
        ),
        migrations.CreateModel(
            name='ProblemasProductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Problemas m\xe1s sentidos como productor',
            },
        ),
        migrations.CreateModel(
            name='ProductosProcesados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('unidad_medida', models.IntegerField(choices=[(1, 'Quintal'), (2, 'Kilogramos'), (3, 'Libras'), (4, 'Docena'), (5, 'Unidad')])),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Productos procesados',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='RecibeCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': '\xbfDe qui\xe9n recibe cr\xe9dito?',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Sistema de Agua',
            },
        ),
        migrations.CreateModel(
            name='TipoEnergia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Tipos de energ\xeda',
            },
        ),
    ]
