# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20170904_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultivo',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Cultivos'},
        ),
    ]
