# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20170908_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afiliacionunag',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Motivos de Afiliaci\xf3n'},
        ),
        migrations.AlterModelOptions(
            name='animales',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='areas',
            options={'ordering': ('nombre',), 'verbose_name': '\xc1rea', 'verbose_name_plural': '\xc1reas'},
        ),
        migrations.AlterModelOptions(
            name='cambioclimatico',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Acciones cambio clim\xe1tico'},
        ),
        migrations.AlterModelOptions(
            name='cooperativa',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Cooperativas'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Documento de propiedad'},
        ),
        migrations.AlterModelOptions(
            name='dondecotiza',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Donde cotiza'},
        ),
        migrations.AlterModelOptions(
            name='formascredito',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Formas en que recibe cr\xe9dito'},
        ),
        migrations.AlterModelOptions(
            name='infraestructuras',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Infraestructuras'},
        ),
        migrations.AlterModelOptions(
            name='origen',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Origen de la Propiedad'},
        ),
        migrations.AlterModelOptions(
            name='problemasproductor',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Problemas m\xe1s sentidos como productor'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='recibecredito',
            options={'ordering': ('nombre',), 'verbose_name_plural': '\xbfDe qui\xe9n recibe cr\xe9dito?'},
        ),
        migrations.AlterModelOptions(
            name='sistema',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Sistema de Agua'},
        ),
    ]
