# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0002_auto_20170712_0834'),
        ('configuracion', '0004_auto_20170920_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoSemilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Departamento')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Bancos de Semillas',
            },
        ),
        migrations.AddField(
            model_name='cultivo',
            name='unidad_medida',
            field=models.IntegerField(blank=True, choices=[(1, 'Quintal'), (2, 'Kilogramos'), (3, 'Libras'), (4, 'Docena'), (5, 'Unidad')], null=True),
        ),
    ]
