# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_tipoenergia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosProcesados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('unidad_medida', models.IntegerField(choices=[(1, 'Quintal'), (2, 'Kilogramos'), (3, 'Libras'), (4, 'Docena'), (5, 'Unidad')])),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name_plural': 'Productos procesados',
            },
        ),
    ]
