# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='extension',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=b'Extension Territorial'),
        ),
    ]
